// <auto-generated />
using DataAccess.Private.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(CustomerOrderContext))]
    [Migration("20230904101516_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Private.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1L,
                            Name = "Carson Alexander",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 2L,
                            Name = "Meredith Alonso",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 3L,
                            Name = "Carson Anand",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 4L,
                            Name = "Arturo Barzdukas",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 5L,
                            Name = "Gytis Li",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 6L,
                            Name = "Yan Justice",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 7L,
                            Name = "Peggy Norman",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 8L,
                            Name = "Laura Olivetto",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 9L,
                            Name = "Nino Alexander",
                            PhoneNumber = "09061111111"
                        },
                        new
                        {
                            CustomerId = 10L,
                            Name = "Samson Alexander",
                            PhoneNumber = "09061111111"
                        });
                });

            modelBuilder.Entity("DataAccess.Private.Models.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1L,
                            Amount = 10.10m,
                            CustomerId = 1L,
                            OrderNumber = 1L
                        },
                        new
                        {
                            OrderId = 2L,
                            Amount = 10.10m,
                            CustomerId = 1L,
                            OrderNumber = 2L
                        },
                        new
                        {
                            OrderId = 5L,
                            Amount = 10.10m,
                            CustomerId = 1L,
                            OrderNumber = 5L
                        },
                        new
                        {
                            OrderId = 6L,
                            Amount = 10.10m,
                            CustomerId = 2L,
                            OrderNumber = 6L
                        },
                        new
                        {
                            OrderId = 7L,
                            Amount = 10.10m,
                            CustomerId = 2L,
                            OrderNumber = 7L
                        },
                        new
                        {
                            OrderId = 9L,
                            Amount = 10.10m,
                            CustomerId = 2L,
                            OrderNumber = 9L
                        },
                        new
                        {
                            OrderId = 10L,
                            Amount = 10.10m,
                            CustomerId = 2L,
                            OrderNumber = 10L
                        },
                        new
                        {
                            OrderId = 11L,
                            Amount = 10.10m,
                            CustomerId = 3L,
                            OrderNumber = 11L
                        },
                        new
                        {
                            OrderId = 12L,
                            Amount = 10.10m,
                            CustomerId = 3L,
                            OrderNumber = 12L
                        },
                        new
                        {
                            OrderId = 15L,
                            Amount = 10.10m,
                            CustomerId = 3L,
                            OrderNumber = 15L
                        },
                        new
                        {
                            OrderId = 21L,
                            Amount = 10.10m,
                            CustomerId = 5L,
                            OrderNumber = 21L
                        },
                        new
                        {
                            OrderId = 22L,
                            Amount = 10.10m,
                            CustomerId = 5L,
                            OrderNumber = 22L
                        },
                        new
                        {
                            OrderId = 23L,
                            Amount = 10.10m,
                            CustomerId = 5L,
                            OrderNumber = 23L
                        },
                        new
                        {
                            OrderId = 24L,
                            Amount = 10.10m,
                            CustomerId = 5L,
                            OrderNumber = 24L
                        },
                        new
                        {
                            OrderId = 25L,
                            Amount = 10.10m,
                            CustomerId = 5L,
                            OrderNumber = 25L
                        },
                        new
                        {
                            OrderId = 26L,
                            Amount = 10.10m,
                            CustomerId = 6L,
                            OrderNumber = 26L
                        },
                        new
                        {
                            OrderId = 27L,
                            Amount = 10.10m,
                            CustomerId = 6L,
                            OrderNumber = 27L
                        },
                        new
                        {
                            OrderId = 28L,
                            Amount = 10.10m,
                            CustomerId = 6L,
                            OrderNumber = 28L
                        },
                        new
                        {
                            OrderId = 29L,
                            Amount = 10.10m,
                            CustomerId = 6L,
                            OrderNumber = 29L
                        },
                        new
                        {
                            OrderId = 30L,
                            Amount = 10.10m,
                            CustomerId = 6L,
                            OrderNumber = 30L
                        },
                        new
                        {
                            OrderId = 31L,
                            Amount = 10.10m,
                            CustomerId = 7L,
                            OrderNumber = 31L
                        },
                        new
                        {
                            OrderId = 32L,
                            Amount = 10.10m,
                            CustomerId = 7L,
                            OrderNumber = 32L
                        },
                        new
                        {
                            OrderId = 33L,
                            Amount = 10.10m,
                            CustomerId = 7L,
                            OrderNumber = 33L
                        },
                        new
                        {
                            OrderId = 35L,
                            Amount = 10.10m,
                            CustomerId = 7L,
                            OrderNumber = 35L
                        },
                        new
                        {
                            OrderId = 36L,
                            Amount = 10.10m,
                            CustomerId = 8L,
                            OrderNumber = 36L
                        },
                        new
                        {
                            OrderId = 37L,
                            Amount = 10.10m,
                            CustomerId = 8L,
                            OrderNumber = 37L
                        },
                        new
                        {
                            OrderId = 38L,
                            Amount = 10.10m,
                            CustomerId = 8L,
                            OrderNumber = 38L
                        },
                        new
                        {
                            OrderId = 39L,
                            Amount = 10.10m,
                            CustomerId = 8L,
                            OrderNumber = 39L
                        },
                        new
                        {
                            OrderId = 40L,
                            Amount = 10.10m,
                            CustomerId = 8L,
                            OrderNumber = 40L
                        },
                        new
                        {
                            OrderId = 41L,
                            Amount = 10.10m,
                            CustomerId = 9L,
                            OrderNumber = 41L
                        },
                        new
                        {
                            OrderId = 44L,
                            Amount = 10.10m,
                            CustomerId = 9L,
                            OrderNumber = 44L
                        },
                        new
                        {
                            OrderId = 45L,
                            Amount = 10.10m,
                            CustomerId = 9L,
                            OrderNumber = 45L
                        },
                        new
                        {
                            OrderId = 46L,
                            Amount = 10.10m,
                            CustomerId = 10L,
                            OrderNumber = 46L
                        },
                        new
                        {
                            OrderId = 47L,
                            Amount = 10.10m,
                            CustomerId = 10L,
                            OrderNumber = 47L
                        },
                        new
                        {
                            OrderId = 49L,
                            Amount = 10.10m,
                            CustomerId = 10L,
                            OrderNumber = 49L
                        },
                        new
                        {
                            OrderId = 50L,
                            Amount = 10.10m,
                            CustomerId = 10L,
                            OrderNumber = 50L
                        });
                });

            modelBuilder.Entity("DataAccess.Private.Models.Order", b =>
                {
                    b.HasOne("DataAccess.Private.Models.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Private.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
